#!/bin/bash
PATH=$PATH:/arm-eabi/bin

rm -rf gmp-6.1.2.tar.bz2
wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2

rm -rf gmp-6.1.2
tar -xvjpf gmp-6.1.2.tar.bz2

cd gmp-6.1.2

./configure \
  --build=x86_64-pc-linux-gnu \
  --host=arm-none-eabi \
  --disable-assembly \
  --disable-shared \
  --disable-fft \
  --disable-werror \
  --disable-cxx \
  LDFLAGS='-Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now' \
  CFLAGS="-nostartfiles --specs=nosys.specs -mcpu=cortex-m4 -O2 -s -pedantic -fomit-frame-pointer -Wa,--noexecstack -ffunction-sections -funwind-tables -no-canonical-prefixes -fno-strict-aliasing -fstack-protector -finline-limit=64 -mthumb -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16" \
  MPN_PATH="arm/v7a arm/v6t2 arm/v5 arm generic"

make -j8 V=1
