#!/bin/bash
#rm -rf gmp-6.1.2.tar.bz2
#wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2
#
#rm -rf gmp-6.1.2
#tar -xvjpf gmp-6.1.2.tar.bz2
#



# The above things were manually done as it is a once-off operation.
# In summary,
#   Download gmp 6.1.2
#   Unzip it in this DMCP_build folder.
#   Run this script
#   That's it.
#
PATH=$PATH:/Users/jacomostert/Documents/WP43S/DM42/gcc-arm-none-eabi-8-2019-q3-update/bin

cd gmp-6.2.0

./configure \
  --host=arm-none-eabi \
  --disable-assembly \
  --disable-shared \
  --disable-fft \
  --disable-werror \
  --disable-cxx \
  LDFLAGS='-Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now' \
  CFLAGS="-nostartfiles --specs=nosys.specs -mcpu=cortex-m4 -Os -s -pedantic -fomit-frame-pointer -Wa,--noexecstack -ffunction-sections -funwind-tables -no-canonical-prefixes -fno-strict-aliasing -fstack-protector -finline-limit=64 -mthumb -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16" \
#  MPN_PATH="arm/v7a arm/v6t2 arm/v5 arm generic"

make -j8 V=1
