#!/bin/bash

PATH=$PATH:/opt/local/include/
PATH=$PATH:/opt/local/
PATH=$PATH:/Users/jacomostert/Documents/WP43S/DM42/gcc-arm-none-eabi-8-2019-q3-update/bin


make clean
make -j8 --debug

mv build/WP43S.pgm build/WP43C.pgm
