#!/bin/bash

PATH=$PATH:/opt/local/include/
PATH=$PATH:/opt/local/
PATH=$PATH:/Users/jacomostert/Documents/WP43S/DM42/gcc-arm-none-eabi-8-2019-q3-update/bin
#PATH=$PATH:/Users/jacomostert/Documents/WP43S/DM42/gcc-arm-none-eabi-10-2020-q2-preview/bin

PATH=$PATH:./bin:/arm-eabi/bin

rm -rf decNumberICU
rm -rf src
ln -s ../decNumberICU
ln -s ../src

rm -rf decNumberICU
rm -rf src
ln -s ../decNumberICU
ln -s ../src

rm src/wp43s/*\ [0-9].c

make clean
make -j8 --silent
#make -j8 --debug

mv build/WP43S.pgm build/WP43C.pgm
cp build/WP43C.pgm ../DM42\ binary/C43.pgm
cp build/WP43S_qspi.bin ../DM42\ binary/C43_qspi.bin
