#!/bin/bash

PATH=$PATH:/Users/jacomostert/Documents/WP43S/DM42/gcc-arm-none-eabi-8-2019-q3-update/bin

make -j8 V=1 clean_all
rm ./backup.bin
rm ./wp43c

make -j8 V=1 mrproper

find build/ -type f -name "*.o" -exec rm {} \;
find build/ -type f -name "*.d" -exec rm {} \;
find src/ -type f -name "*.o" -exec rm {} \;
find src/ -type f -name "*.d" -exec rm {} \;
find build.dmcp/ -type f -name "*.o" -exec rm {} \;
find build.dmcp/ -type f -name "*.d" -exec rm {} \;
find build.sim/ -type f -name "*.o" -exec rm {} \;
find build.sim/ -type f -name "*.d" -exec rm {} \;

find . -type f -name "*.dSYM" -exec rm {} \;
find . -type f -name ".DS_Store" -exec rm {} \;

