/* This file is part of 43S.
 *
 * 43S is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * 43S is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with 43S.  If not, see <http://www.gnu.org/licenses/>.
 */

/********************************************//**
* \file constantPointers.h constants
***********************************************/

/************************************************************************************************
* Do not edit this file manually! It's automagically generated by the program generateConstants *
*************************************************************************************************/

#define CONST_00    0
#define CONST_01   36
#define CONST_02   72
#define CONST_03  108
#define CONST_04  144
#define CONST_05  180
#define CONST_06  216
#define CONST_07  252
#define CONST_08  288
#define CONST_09  324
#define CONST_10  360
#define CONST_11  396
#define CONST_12  432
#define CONST_13  468
#define CONST_14  504
#define CONST_15  540
#define CONST_16  576
#define CONST_17  612
#define CONST_18  648
#define CONST_19  684
#define CONST_20  720
#define CONST_21  756
#define CONST_22  792
#define CONST_23  828
#define CONST_24  864
#define CONST_25  900
#define CONST_26  936
#define CONST_27  972
#define CONST_28 1008
#define CONST_29 1044
#define CONST_30 1080
#define CONST_31 1116
#define CONST_32 1152
#define CONST_33 1188
#define CONST_34 1224
#define CONST_35 1260
#define CONST_36 1296
#define CONST_37 1332
#define CONST_38 1368
#define CONST_39 1404
#define CONST_40 1440
#define CONST_41 1476
#define CONST_42 1512
#define CONST_43 1548
#define CONST_44 1584
#define CONST_45 1620
#define CONST_46 1656
#define CONST_47 1692
#define CONST_48 1728
#define CONST_49 1764
#define CONST_50 1800
#define CONST_51 1836
#define CONST_52 1872
#define CONST_53 1908
#define CONST_54 1944
#define CONST_55 1980
#define CONST_56 2016
#define CONST_57 2052
#define CONST_58 2088
#define CONST_59 2124
#define CONST_60 2160
#define CONST_61 2196
#define CONST_62 2232
#define CONST_63 2268
#define CONST_64 2304
#define CONST_65 2340
#define CONST_66 2376
#define CONST_67 2412
#define CONST_68 2448
#define CONST_69 2484
#define CONST_70 2520
#define CONST_71 2556
#define CONST_72 2592
#define CONST_73 2628
#define CONST_74 2664
#define CONST_75 2700
#define CONST_76 2736
#define CONST_77 2772
#define CONST_78 2808
#define CONST_79 2844

extern const uint8_t constants[];
extern const realIc_t * const const_1on2;
extern const realIc_t * const const_a;
extern const realIc_t * const const_a0;
extern const realIc_t * const const_aM;
extern const realIc_t * const const_aEarth;
extern const realIc_t * const const_c;
extern const realIc_t * const const_c1;
extern const realIc_t * const const_c2;
extern const realIc_t * const const_e;
extern const realIc_t * const const_eE;
extern const realIc_t * const const_eme;
extern const realIc_t * const const_F;
extern const realIc_t * const const_Falpha;
extern const realIc_t * const const_Fdelta;
extern const realIc_t * const const_G;
extern const realIc_t * const const_G0;
extern const realIc_t * const const_GC;
extern const realIc_t * const const_ge;
extern const realIc_t * const const_GM;
extern const realIc_t * const const_gEarth;
extern const realIc_t * const const_Planck;
extern const realIc_t * const const_PlanckOn2pi;
extern const realIc_t * const const_k;
extern const realIc_t * const const_KJ;
extern const realIc_t * const const_lp;
extern const realIc_t * const const_me;
extern const realIc_t * const const_MM;
extern const realIc_t * const const_mn;
extern const realIc_t * const const_mnOnmp;
extern const realIc_t * const const_mPL;
extern const realIc_t * const const_mp;
extern const realIc_t * const const_mpOnme;
extern const realIc_t * const const_mu;
extern const realIc_t * const const_muc2;
extern const realIc_t * const const_mmu;
extern const realIc_t * const const_mSun;
extern const realIc_t * const const_mEarth;
extern const realIc_t * const const_NA;
extern const realIc_t * const const_NaN;
extern const realIc_t * const const_p0;
extern const realIc_t * const const_R;
extern const realIc_t * const const_re;
extern const realIc_t * const const_RK;
extern const realIc_t * const const_RM;
extern const realIc_t * const const_RInfinity;
extern const realIc_t * const const_RSun;
extern const realIc_t * const const_REarth;
extern const realIc_t * const const_Sa;
extern const realIc_t * const const_Sb;
extern const realIc_t * const const_Se2;
extern const realIc_t * const const_Sep2;
extern const realIc_t * const const_Sfm1;
extern const realIc_t * const const_T0;
extern const realIc_t * const const_TP;
extern const realIc_t * const const_tp;
extern const realIc_t * const const_Vm;
extern const realIc_t * const const_Z0;
extern const realIc_t * const const_alpha;
extern const realIc_t * const const_gamma;
extern const realIc_t * const const_gammaEM;
extern const realIc_t * const const_gammap;
extern const realIc_t * const const_epsilon0;
extern const realIc_t * const const_lambdaC;
extern const realIc_t * const const_lambdaCn;
extern const realIc_t * const const_lambdaCp;
extern const realIc_t * const const_mu0;
extern const realIc_t * const const_muB;
extern const realIc_t * const const_mue;
extern const realIc_t * const const_mueOnmuB;
extern const realIc_t * const const_mun;
extern const realIc_t * const const_mup;
extern const realIc_t * const const_muu;
extern const realIc_t * const const_mumu;
extern const realIc_t * const const_sigmaB;
extern const realIc_t * const const_PHI;
extern const realIc_t * const const_PHI0;
extern const realIc_t * const const_omega;
extern const realIc_t * const const_minusInfinity;
extern const realIc_t * const const_plusInfinity;
extern const realIc_t * const const_0;
extern const realIc_t * const const_gammaC00;
extern const realIc_t * const const_gammaC01;
extern const realIc_t * const const_gammaC02;
extern const realIc_t * const const_gammaC03;
extern const realIc_t * const const_gammaC04;
extern const realIc_t * const const_gammaC05;
extern const realIc_t * const const_gammaC06;
extern const realIc_t * const const_gammaC07;
extern const realIc_t * const const_gammaC08;
extern const realIc_t * const const_gammaC09;
extern const realIc_t * const const_gammaC10;
extern const realIc_t * const const_gammaC11;
extern const realIc_t * const const_gammaC12;
extern const realIc_t * const const_gammaC13;
extern const realIc_t * const const_gammaC14;
extern const realIc_t * const const_gammaC15;
extern const realIc_t * const const_gammaC16;
extern const realIc_t * const const_gammaC17;
extern const realIc_t * const const_gammaC18;
extern const realIc_t * const const_gammaC19;
extern const realIc_t * const const_gammaC20;
extern const realIc_t * const const_gammaC21;
extern const realIc_t * const const_180;
extern const realIc_t * const const_200;
extern const realIc_t * const const_pi;
extern const realIc_t * const const_1;
extern const realIc_t * const const_90;
extern const realIc_t * const const_100;
extern const realIc_t * const const_piOn2;
extern const realIc_t * const const_0_5;
extern const realIc_t * const const_45;
extern const realIc_t * const const_50;
extern const realIc_t * const const_piOn4;
extern const realIc_t * const const_1on4;
extern const realIc_t * const const_PointToM;
extern const realIc_t * const const_InchToM;
extern const realIc_t * const const_FtToM;
extern const realIc_t * const const_SfeetToM;
extern const realIc_t * const const_YardToM;
extern const realIc_t * const const_FathomToM;
extern const realIc_t * const const_MiToM;
extern const realIc_t * const const_NmiToM;
extern const realIc_t * const const_AuToM;
extern const realIc_t * const const_LyToM;
extern const realIc_t * const const_PcToM;
extern const realIc_t * const const_AccreToM2;
extern const realIc_t * const const_AccreusToM2;
extern const realIc_t * const const_FlozukToM3;
extern const realIc_t * const const_FlozusToM3;
extern const realIc_t * const const_GalusToM3;
extern const realIc_t * const const_GalukToM3;
extern const realIc_t * const const_QuartToM3;
extern const realIc_t * const const_BarrelToM3;
extern const realIc_t * const const_CaratToKg;
extern const realIc_t * const const_OzToKg;
extern const realIc_t * const const_TrozToKg;
extern const realIc_t * const const_LbToKg;
extern const realIc_t * const const_StoneToKg;
extern const realIc_t * const const_ShortcwtToKg;
extern const realIc_t * const const_CwtToKg;
extern const realIc_t * const const_ShorttonToKg;
extern const realIc_t * const const_TonToKg;
extern const realIc_t * const const_CalToJ;
extern const realIc_t * const const_BtuToJ;
extern const realIc_t * const const_WhToJ;
extern const realIc_t * const const_LbfToN;
extern const realIc_t * const const_TorrToPa;
extern const realIc_t * const const_InhgToPa;
extern const realIc_t * const const_PsiToPa;
extern const realIc_t * const const_BarToPa;
extern const realIc_t * const const_AtmToPa;
extern const realIc_t * const const_HpmToW;
extern const realIc_t * const const_HpukToW;
extern const realIc_t * const const_HpeToW;
extern const realIc_t * const const_YearToS;
extern const realIc_t * const const__1;
extern const realIc_t * const const_1e_37;
extern const realIc_t * const const_1e_24;
extern const realIc_t * const const_1e_6;
extern const realIc_t * const const_1e_4;
extern const realIc_t * const const_1on10;
extern const realIc_t * const const_1on3;
extern const realIc_t * const const_egamma;
extern const realIc_t * const const_ln2;
extern const realIc_t * const const_root2on2;
extern const realIc_t * const const_9on10;
extern const realIc_t * const const_9on5;
extern const realIc_t * const const_2;
extern const realIc_t * const const_ln10;
extern const realIc_t * const const_3piOn4;
extern const realIc_t * const const_3;
extern const realIc_t * const const_5;
extern const realIc_t * const const_2pi;
extern const realIc_t * const const_10;
extern const realIc_t * const const_20;
extern const realIc_t * const const_21;
extern const realIc_t * const const_gammaR;
extern const realIc_t * const const_32;
extern const realIc_t * const const_36;
extern const realIc_t * const const_47;
extern const realIc_t * const const_180onPi;
extern const realIc_t * const const_60;
extern const realIc_t * const const_200onPi;
extern const realIc_t * const const_204;
extern const realIc_t * const const_360;
extern const realIc_t * const const_400;
extern const realIc_t * const const_1000;
extern const realIc_t * const const_3600;
extern const realIc_t * const const_9999;
extern const realIc_t * const const_10000;
extern const realIc_t * const const_1e6;
extern const realIc_t * const const_2p32;
extern const realIc_t * const const451_2pi;
extern const real16_t * const const16_0;
extern const real16_t * const const16_1e_4;
extern const real16_t * const const16_1;
extern const real16_t * const const16_2pi;
extern const real16_t * const const16_1000;
extern const real16_t * const const16_1e6;
extern const real34_t * const const34_0;
extern const real34_t * const const34_1e_6;
extern const real34_t * const const34_1e_4;
extern const real34_t * const const34_1on2;
extern const real34_t * const const34_1;
extern const real34_t * const const34_2pi;
extern const real34_t * const const34_1000;
extern const real34_t * const const34_1e6;
