/* This file is part of 43S.
 *
 * 43S is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * 43S is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with 43S.  If not, see <http://www.gnu.org/licenses/>.
 */

/********************************************//**
* \file constantPointers.h constants
***********************************************/

/************************************************************************************************
* Do not edit this file manually! It's automagically generated by the program generateConstants *
*************************************************************************************************/

#define CONST_00    0
#define CONST_01    8
#define CONST_02   16
#define CONST_03   24
#define CONST_04   32
#define CONST_05   40
#define CONST_06   48
#define CONST_07   56
#define CONST_08   64
#define CONST_09   72
#define CONST_10   80
#define CONST_11   88
#define CONST_12   96
#define CONST_13  104
#define CONST_14  112
#define CONST_15  120
#define CONST_16  128
#define CONST_17  136
#define CONST_18  144
#define CONST_19  152
#define CONST_20  160
#define CONST_21  168
#define CONST_22  176
#define CONST_23  184
#define CONST_24  192
#define CONST_25  200
#define CONST_26  208
#define CONST_27  216
#define CONST_28  224
#define CONST_29  232
#define CONST_30  240
#define CONST_31  248
#define CONST_32  256
#define CONST_33  264
#define CONST_34  272
#define CONST_35  280
#define CONST_36  288
#define CONST_37  296
#define CONST_38  304
#define CONST_39  312
#define CONST_40  320
#define CONST_41  328
#define CONST_42  336
#define CONST_43  344
#define CONST_44  352
#define CONST_45  360
#define CONST_46  368
#define CONST_47  376
#define CONST_48  384
#define CONST_49  392
#define CONST_50  400
#define CONST_51  408
#define CONST_52  416
#define CONST_53  424
#define CONST_54  432
#define CONST_55  440
#define CONST_56  448
#define CONST_57  456
#define CONST_59  464
#define CONST_60  472
#define CONST_61  480
#define CONST_62  488
#define CONST_63  496
#define CONST_64  504
#define CONST_65  512
#define CONST_66  520
#define CONST_67  528
#define CONST_68  536
#define CONST_69  544
#define CONST_70  552
#define CONST_71  560
#define CONST_72  568
#define CONST_73  576
#define CONST_74  584
#define CONST_75  592
#define CONST_76  600
#define CONST_77  608
#define CONST_78  616
#define CONST_79  624

extern const uint8_t constants[];
extern const real16_t * const const16_0_5;
extern const real16_t * const const16_a;
extern const real16_t * const const16_a0;
extern const real16_t * const const16_aM;
extern const real16_t * const const16_aEarth;
extern const real16_t * const const16_c;
extern const real16_t * const const16_c1;
extern const real16_t * const const16_c2;
extern const real16_t * const const16_e;
extern const real16_t * const const16_eE;
extern const real16_t * const const16_eme;
extern const real16_t * const const16_F;
extern const real16_t * const const16_Falpha;
extern const real16_t * const const16_Fdelta;
extern const real16_t * const const16_G;
extern const real16_t * const const16_G0;
extern const real16_t * const const16_GC;
extern const real16_t * const const16_ge;
extern const real16_t * const const16_GM;
extern const real16_t * const const16_gEarth;
extern const real16_t * const const16_Planck;
extern const real16_t * const const16_PlanckOn2pi;
extern const real16_t * const const16_k;
extern const real16_t * const const16_KJ;
extern const real16_t * const const16_lp;
extern const real16_t * const const16_me;
extern const real16_t * const const16_MM;
extern const real16_t * const const16_mn;
extern const real16_t * const const16_mnOnmp;
extern const real16_t * const const16_mPL;
extern const real16_t * const const16_mp;
extern const real16_t * const const16_mpOnme;
extern const real16_t * const const16_mu;
extern const real16_t * const const16_muc2;
extern const real16_t * const const16_mmu;
extern const real16_t * const const16_mSun;
extern const real16_t * const const16_mEarth;
extern const real16_t * const const16_NA;
extern const real16_t * const const16_NaN;
extern const real16_t * const const16_p0;
extern const real16_t * const const16_R;
extern const real16_t * const const16_re;
extern const real16_t * const const16_RK;
extern const real16_t * const const16_RM;
extern const real16_t * const const16_RInfinity;
extern const real16_t * const const16_RSun;
extern const real16_t * const const16_REarth;
extern const real16_t * const const16_Sa;
extern const real16_t * const const16_Sb;
extern const real16_t * const const16_Se2;
extern const real16_t * const const16_Sep2;
extern const real16_t * const const16_Sfm1;
extern const real16_t * const const16_T0;
extern const real16_t * const const16_TP;
extern const real16_t * const const16_tp;
extern const real16_t * const const16_Vm;
extern const real16_t * const const16_Z0;
extern const real16_t * const const16_alpha;
extern const real16_t * const const16_gammaEM;
extern const real16_t * const const16_gammap;
extern const real16_t * const const16_epsilon0;
extern const real16_t * const const16_lambdaC;
extern const real16_t * const const16_lambdaCn;
extern const real16_t * const const16_lambdaCp;
extern const real16_t * const const16_mu0;
extern const real16_t * const const16_muB;
extern const real16_t * const const16_mue;
extern const real16_t * const const16_mueOnmuB;
extern const real16_t * const const16_mun;
extern const real16_t * const const16_mup;
extern const real16_t * const const16_muu;
extern const real16_t * const const16_mumu;
extern const real16_t * const const16_sigmaB;
extern const real16_t * const const16_PHI;
extern const real16_t * const const16_PHI0;
extern const real16_t * const const16_omega;
extern const real16_t * const const16_minusInfinity;
extern const real16_t * const const16_plusInfinity;
extern const real16_t * const const16_0;
extern const real16_t * const const16_1e_4;
extern const real16_t * const const16_ln2;
extern const real16_t * const const16_1;
extern const real16_t * const const16_2;
extern const real16_t * const const16_ln10;
extern const real16_t * const const16_pi;
extern const real16_t * const const16_2pi;
extern const real16_t * const const16_10;
extern const real16_t * const const16_20;
extern const real16_t * const const16_32;
extern const real16_t * const const16_60;
extern const real16_t * const const16_100;
extern const real16_t * const const16_1000;
extern const real16_t * const const16_9999;
extern const real16_t * const const16_10000;
extern const real16_t * const const16_1e6;
extern const real34_t * const const34_FlozukToM3;
extern const real34_t * const const34_FlozusToM3;
extern const real34_t * const const34_CaratToKg;
extern const real34_t * const const34_PointToM;
extern const real34_t * const const34_GalusToM3;
extern const real34_t * const const34_GalukToM3;
extern const real34_t * const const34_QuartToM3;
extern const real34_t * const const34_InchToM;
extern const real34_t * const const34_OzToKg;
extern const real34_t * const const34_TrozToKg;
extern const real34_t * const const34_FtToM;
extern const real34_t * const const34_BarrelToM3;
extern const real34_t * const const34_SfeetToM;
extern const real34_t * const const34_LbToKg;
extern const real34_t * const const34_YardToM;
extern const real34_t * const const34_FathomToM;
extern const real34_t * const const34_CalToJ;
extern const real34_t * const const34_StoneToKg;
extern const real34_t * const const34_LbfToN;
extern const real34_t * const const34_ShortcwtToKg;
extern const real34_t * const const34_CwtToKg;
extern const real34_t * const const34_TorrToPa;
extern const real34_t * const const34_HpmToW;
extern const real34_t * const const34_HpukToW;
extern const real34_t * const const34_ShorttonToKg;
extern const real34_t * const const34_HpeToW;
extern const real34_t * const const34_TonToKg;
extern const real34_t * const const34_BtuToJ;
extern const real34_t * const const34_MiToM;
extern const real34_t * const const34_NmiToM;
extern const real34_t * const const34_InhgToPa;
extern const real34_t * const const34_WhToJ;
extern const real34_t * const const34_AccreToM2;
extern const real34_t * const const34_AccreusToM2;
extern const real34_t * const const34_PsiToPa;
extern const real34_t * const const34_BarToPa;
extern const real34_t * const const34_AtmToPa;
extern const real34_t * const const34_YearToS;
extern const real34_t * const const34_AuToM;
extern const real34_t * const const34_LyToM;
extern const real34_t * const const34_PcToM;
extern const real34_t * const const34_NaN;
extern const real34_t * const const34_minusInfinity;
extern const real34_t * const const34_0;
extern const real34_t * const const34_1e_24;
extern const real34_t * const const34_1e_6;
extern const real34_t * const const34_1e_4;
extern const real34_t * const const34_0_1;
extern const real34_t * const const34_0_5;
extern const real34_t * const const34_egamma;
extern const real34_t * const const34_ln2;
extern const real34_t * const const34_root2on2;
extern const real34_t * const const34_piOn4;
extern const real34_t * const const34_1;
extern const real34_t * const const34_piOn2;
extern const real34_t * const const34_1_8;
extern const real34_t * const const34_2;
extern const real34_t * const const34_ln10;
extern const real34_t * const const34_3piOn4;
extern const real34_t * const const34_3;
extern const real34_t * const const34_pi;
extern const real34_t * const const34_3piOn2;
extern const real34_t * const const34_5;
extern const real34_t * const const34_10;
extern const real34_t * const const34_20;
extern const real34_t * const const34_32;
extern const real34_t * const const34_36;
extern const real34_t * const const34_60;
extern const real34_t * const const34_100;
extern const real34_t * const const34_180;
extern const real34_t * const const34_204;
extern const real34_t * const const34_360;
extern const real34_t * const const34_400;
extern const real34_t * const const34_10000;
extern const real34_t * const const34_1e6;
extern const real34_t * const const34_plusInfinity;
extern const real51_t * const const51_minusInfinity;
extern const real51_t * const const51_NaN;
extern const real51_t * const const51_0;
extern const real51_t * const const51_1e_37;
extern const real51_t * const const51_0_5;
extern const real51_t * const const51_ln2;
extern const real51_t * const const51_root2on2;
extern const real51_t * const const51_1;
extern const real51_t * const const51_2;
extern const real51_t * const const51_ln10;
extern const real51_t * const const51_3;
extern const real51_t * const const51_21;
extern const real51_t * const const51_gammaR;
extern const real51_t * const const51_plusInfinity;
extern const real51_t * const const51_gammaC00;
extern const real51_t * const const51_9on10;
extern const real51_t * const const51_pi;
extern const real51_t * const const51_180onPi;
extern const real51_t * const const51_60;
extern const real51_t * const const51_200onPi;
extern const real51_t * const const51_180;
extern const real51_t * const const51_200;
extern const real51_t * const const51_360;
extern const real51_t * const const51_400;
extern const real51_t * const const51_3600;
extern const real451_t * const const451_2pi;
